name: Build RVMob (non-release)

on:
  push:

jobs: 
  build-win:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
            node-version: 18
            cache: "yarn"
      - name: Install and prepare dependencies
        run: yarn install && npx rn-nodeify -e
      - name: Build the app
        run: npx react-native build-android --mode debug
      - name: Upload debug APK
        uses: actions/upload-artifact@v3
        with: 
          path: D:\a\rvmob\rvmob\android\app\build\outputs\apk\debug\app-debug.apk
          name: RVMob-Debug-${{ github.sha }}.apk
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
            node-version: 18
            cache: "yarn"
      - name: Install and prepare dependencies
        run: yarn install && npx rn-nodeify -e
      - name: Build the app
        run: npx react-native build-android --mode debug
      - name: Upload debug APK
        uses: actions/upload-artifact@v3
        with: 
          path: ~/android/app/build/outputs/apk/debug/app-debug.apk
          name: RVMob-Debug-${{ github.sha }}.apk